### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter position BannerImageHolder{42a3d21 position=0 id=-1, oldPos=-1, pLpos:-1 no parent} 

### ISSUE THREAD

**Issue by KevinSgun** [youth5201314/banner#1103]
程序运行一段时间后就报错crash了，这个错误，怎么处理
Process: com.xincheng1.chat, PID: 19664
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBannerImageHolder{42a3d21 position=0 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{9239ab8 VFED..... ......ID 0,0-1080,255 #5}, adapter:com.xincheng1.chat.ui.anchor.adapter.AnchorListAdapter$HeaderHold$1@f9d2091, layout:com.youth.banner.util.ScrollSpeedManger@6f93bf6, context:com.xincheng1.chat.ui.MainActivity@45dfd80
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6156)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6339)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6517)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by zhidaoshijiejintou** [comment]
我也遇到同样的问题解决了吗

**Comment by mayer500** [comment]
这问题有没有不需要下载源码修改的方法去处理的

**Comment by pengxiyang** [comment]
https://github.com/youth5201314/banner/issues/1195#issuecomment-1831072353
