### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by XD-Z** [youth5201314/banner#1195]
java,lang.IndexOutOfBoundsException: Inconsistency detected,Invalid item positi 5(0Ffset:5)state6 androidx,viewpader2.widaetViewPager2$RecyclerViewlmplid7f386e VFED..... ........ 0,0-1024,766 #5, adapter:com.bool.loncin.ui.circle.adapterBicoseRecommendBannerAdapter6570bbf,layout:com.youth.banner,util.ScrollSpeedlanger0698679, context:com.bool.loncin.ui.mainMainActivity@8ef4f9c
at androidx.recyclerview.widgetRecyclerViewSRecyclertrybetViewHolderForPositionByleadline(RecyclerViem.java:6364)at androidx.recyclerview.widget.Gapllorker.prefetchPositionW/ithDeadline(GapWorker.java:288)at androidx.recyclerview,widget. Gaplorker,flushTaskWithDeadline(GapWorker,iava:345)at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(Gapllorker.java:361)at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.Toop(Looper.java:233)
at android.app.ActivityThread.main(ActivityThread.java:8068)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller,run(RuntimeInit.java:631)at com,android.internal.os,ZygoteInit,main(ZygoteInit,iava:978)

**Comment by byzyhm** [comment]
遇到了，去复现一下

**Comment by pengxiyang** [comment]
![Uploading image.png…]()  我在网上看个了博主说的，数据清除了就立刻刷新

**Comment by pengxiyang** [comment]
![ffdf130e9ddfa649a53c99144a1d4da](https://github.com/youth5201314/banner/assets/72858773/3053125f-838e-46ec-80ee-40a0155e6626)

 @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
        try {
            //try catch一下
            super.onLayoutChildren(recycler, state);
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
        }
    }
这个方法我试了依然闪退，上面图是我按照网上博主建议写的，数据清除时就刷新界面，然后好了
