### ISSUE TITLE
gradle今天更新1.2.3之后出现错误 Caused by: java.lang.NoSuchFieldError: No static field indicatorInside of type I in class Lcom/youth/banner/R$id; or its superclasses (declaration of 'com.youth.banner.R$id' 

### ISSUE THREAD

**Issue by h31639347** [youth5201314/banner#13]
好像是找不到id.不过看了代码layout文件里又这个id,换换1.2.1之后就正常了...

**Comment by youth5201314** [comment]
能发一个完整的日志吗？因为我这确实没有问题。还有你是compile 依赖的吗

**Comment by youth5201314** [comment]
你的xml命名空间是否是http://schemas.android.com/apk/res-auto？

**Comment by h31639347** [comment]
Process: com.doralife.app, PID: 16122
                                                                  android.view.InflateException: Binary XML file line #106: Error inflating class com.youth.banner.Banner
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
                                                                      at com.doralife.app.modules.home.ui.TestHomeFragment.onCreateView(TestHomeFragment.java:101)
                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
                                                                      at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:585)
                                                                      at android.support.v4.app.FragmentTabHost.onAttachedToWindow(FragmentTabHost.java:283)
                                                                      at android.view.View.dispatchAttachedToWindow(View.java:13571)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2690)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697)
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1343)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6186)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:606)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:575)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5595)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:626)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:825) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:523) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:425) 
                                                                      at com.doralife.app.modules.home.ui.TestHomeFragment.onCreateView(TestHomeFragment.java:101) 
                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671) 
                                                                      at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:585) 
                                                                      at android.support.v4.app.FragmentTabHost.onAttachedToWindow(FragmentTabHost.java:283) 
                                                                      at android.view.View.dispatchAttachedToWindow(View.java:13571) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2690) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1343) 
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105) 
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6186) 
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793) 
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:606) 
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:575) 
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5595) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                   Caused by: java.lang.NoSuchFieldError: No static field indicatorInside of type I in class Lcom/youth/banner/R$id; or its superclasses (declaration of 'com.youth.banner.R$id' appears in /data/app/com.doralife.app-2/base.apk)
                                                                      at com.youth.banner.Banner.initView(Banner.java:110)
                                                                      at com.youth.banner.Banner.<init>(Banner.java:88)
                                                                      at com.youth.banner.Banner.<init>(Banner.java:80)
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:626) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:825) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:828) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:523) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:425) 
                                                                      at com.doralife.app.modules.home.ui.TestHomeFragment.onCreateView(TestHomeFragment.java:101) 
                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104) 
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671) 
                                                                      at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:585) 
                                                                      at android.support.v4.app.FragmentTabHost.onAttachedToWindow(FragmentTabHost.java:283) 
                                                                      at android.view.View.dispatchAttachedToWindow(View.java:13571) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2690) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2697) 
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1343) 
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105) 
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6186) 
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793) 
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:606) 
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:575) 
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5595) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by h31639347** [comment]
可能是我得项目环境有影响或者冲突。资源layout是有id得。但是变异后在R文件中没有，但是也能编译成功运行，开始在linux下以为是as版本问题，换成win也不行。命名空间也是正确得。应该是项目有影响到了编译。谢谢回答。也谢谢您得开源代码。
