### ISSUE TITLE
更新数据的时候有时会crash

### ISSUE THREAD

**Issue by qiulei19850103** [youth5201314/banner#197]
java.lang.ArithmeticException: divide by zero
	at com.youth.banner.Banner.onPageSelected(Banner.java:579)
	at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1867)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:604)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:551)
	at com.youth.banner.Banner.setData(Banner.java:426)
	at com.youth.banner.Banner.start(Banner.java:263)
	at com.youth.banner.Banner.update(Banner.java:246)
	at com.jartoo.mylib.activity.main.HomeFragment.updateSlider(HomeFragment.java:2012)
	at com.jartoo.mylib.activity.main.HomeFragment.access$4100(HomeFragment.java:117)
	at com.jartoo.mylib.activity.main.HomeFragment$27.run(HomeFragment.java:2301)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by willqian** [comment]
是不是imageUrls为空了

**Comment by qiulei19850103** [comment]
有判断空指针的操作。

**Comment by gxh-apologize** [comment]
请问解决了吗
