### ISSUE TITLE
这又是怎么回事

### ISSUE THREAD

**Issue by qssq** [youth5201314/banner#215]
Build version: 2.2 
Build date: 1979-11-30 00:00:00 
Current date: 2017-05-26 14:23:46 
Device: Sony E5823 
 
Stack trace:  
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 6, found: 0 Pager id: com.buyao.tv:id/bannerViewPager Pager class: class com.youth.banner.view.BannerViewPager Problematic adapter: class com.youth.banner.Banner$BannerPagerAdapter
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1167)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:543)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5045)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by qssq** [comment]
部分问题是我把volley的解析提取到后台 导致在子线程导致 ，目前好像没问题了。
