### ISSUE TITLE
recyclerview 直接scrollposition 到banner位置 就出问题了，各种适配器没刷新啊什么的，但是我直接下拉刷新没问题

### ISSUE THREAD

**Issue by qssq** [youth5201314/banner#216]
希望大佬测试一下这是么子情况。  之前项目需求不变态的时候bug都没有的最近bug吓死人。

**Comment by qssq** [comment]
出现了一下几种问题：  1：view不绘制 图片 ，我调整到初始化item的时候再加载图片搞定了，  
问题2：动画没了 变成了图片然后闪成banner的颜色 然后再再出现图片，原因，使用scrollposition 

问题3：也是scrollposition 导致 直接崩溃了。

**Comment by qssq** [comment]
Stack trace:  
                                              java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 6, found: 0 Pager id: com.buyao.tv:id/bannerViewPager Pager class: class cn.qssq666.banner.view.BannerViewPager Problematic adapter: class cn.qssq666.banner.Banner$BannerPagerAdapter
                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1167)
                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                  at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                  at android.view.Choreographer.doFrame(Choreographer.java:664)
                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
                                                  at android.os.Handler.handleCallback(Handler.java:761)
                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                  at android.os.Looper.loop(Looper.java:156)
                                                  at android.app.ActivityThread.main(ActivityThread.java:6531)
                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by qssq** [comment]
3： 你得那种设置striing的写法很不好，网络上的都市模型的，你应该定义一个接口。我已经改造了，不知道我们可以合并项目吗

**Comment by qssq** [comment]
被我乱改一通 崩溃问题解决了，但是猛点 scrllltoposition 动画都不能动了。手动滑动变成 拖动了根本滑动不了

**Comment by 1226362423** [comment]
怎么解决这个问题的啊
