### ISSUE TITLE
通过mBanner.update(new ArrayList<>());后，报下标越界错误。

### ISSUE THREAD

**Issue by kinshasa** [youth5201314/banner#249]
通过mBanner.update(new ArrayList<>());后，报下标越界错误。
E/banner: Please set the images data.

  Caused by: java.lang.ArithmeticException: divide by zero
                                                                        at com.youth.banner.Banner.onPageSelected(Banner.java:578)
                                                                        at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1967)
                                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:664)
                                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                        at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
                                                                        at com.youth.banner.Banner.setData(Banner.java:426)
                                                                        at com.youth.banner.Banner.start(Banner.java:263)
                                                                        at com.youth.banner.Banner.update(Banner.java:246)

**Comment by bluerheaven** [comment]
我也遇到了同样的问题。
只能通过setImages更新图片，会出现刚开始2s的滑动卡顿

**Comment by protectedMan** [comment]
这个错误是ArithmeticException，除数不能为零的错误。
