### ISSUE TITLE
将banner嵌套到RecyclerView时快速滑动RecyclerView会出现崩溃问题

### ISSUE THREAD

**Issue by skytang168** [youth5201314/banner#491]
Process: com.yf.yftrace.app, PID: 22599
    java.lang.ArithmeticException: divide by zero
        at com.youth.banner.Banner.onPageSelected(Banner.java:586)
        at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1941)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:659)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
        at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:606)
        at com.youth.banner.Banner.setData(Banner.java:433)
        at com.youth.banner.Banner.start(Banner.java:270)
        at com.yf.yftrace.arms.mvp.adpter.PestAdapter.convert(PestAdapter.java:56)
        at com.yf.yftrace.arms.mvp.adpter.PestAdapter.convert(PestAdapter.java:17)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:919)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5609)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:771)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)

**Comment by AricGuo** [comment]
请问你这种使用方式是讲banner作为recycleview 一个cell吗

**Comment by skytang168** [comment]
找到原因了，我是把banner作为recycleview 的一个item来使用的，当时数据不完整，如果图片数量为0，快速滑动的时候就会报错，所以图片的数量必须大于0.
