### ISSUE TITLE
Error inflating class com.youth.banner.Banner

### ISSUE THREAD

**Issue by zhuyonghao** [youth5201314/banner#520]
报错：
Error inflating class com.youth.banner.Banner
但是可以点击进去

1.Gradle版本3.2.1
2.implementation或者api方式集成
3.kotlin+androidx项目

![image](https://user-images.githubusercontent.com/18735317/47539377-aec35900-d902-11e8-954a-ac840e871a72.png)

具体报错
![image](https://user-images.githubusercontent.com/18735317/47539452-1f6a7580-d903-11e8-8d74-05b11f038744.png)

  android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class com.youth.banner.Banner
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.vec.nativeapp.ui.product.ProductInfoFragment.onCreateView(ProductInfoFragment.kt:42)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:146)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:19388)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:991)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
        at android.view.View.measure(View.java:19388)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:19388)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
        at android.view.View.measure(View.java:19388)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
        at android.view.View.measure(View.java:19388)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
        at android.view.View.measure(View.java:19388)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2733)
        at android.view.View.measure(View.java:19388)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2552)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1457)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1720)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1338)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6872)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:899)
        at android.view.Choreographer.doCallbacks(Choreographer.java:701)
        at android.view.Choreographer.doFrame(Choreographer.java:636)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:885)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
    	at android.app.ActivityThre
10-26 09:37:38.347 21055-21192/com.vec.nativeapp E/CellLocation: create GsmCellLocation
10-26 09:37:38.354 21055-21192/com.vec.nativeapp E/CellLocation: create GsmCellLocation

**Comment by zhuyonghao** [comment]
已经找到原因Banner 的id 为bannerTitle 可能与你这边冲突导致

**Comment by luyuan11233** [comment]
我也遇到了这个问题，然而我这边是怎么改都报这个错，

**Comment by IHoveYou** [comment]
我也遇到了这个问题，修改ID并没有用
