### ISSUE TITLE
android 4.4.4 oppo R7 API19 crash

### ISSUE THREAD

**Issue by chichengjunma** [youth5201314/banner#524]
android 4.4.4 oppo R7 API19 crash！！！！！！！！

CrashHandler: In thread: Thread[main,5,main]
                                                            UncaughtException detected: android.view.InflateException: Binary XML file line #19: Error inflating class com.youth.banner.Banner
                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353)

**Comment by liuyongyi0110** [comment]
you can set the propity :  app:banner_default_image="@mipmap/ic_launcher"
