### ISSUE TITLE
Demo下拉 报错 throwIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zzzlw** [youth5201314/banner#54]
`11-15 14:38:22.222 20758-20758/com.test.banner E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.test.banner, PID: 20758
                                                                 java.lang.IndexOutOfBoundsException: Invalid index 6, size is 6
                                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                                     at com.youth.banner.Banner$BannerPagerAdapter.destroyItem(Banner.java:428)
                                                                     at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:474)
                                                                     at com.youth.banner.Banner.setData(Banner.java:344)
                                                                     at com.youth.banner.Banner.setImageList(Banner.java:311)
                                                                     at com.youth.banner.Banner.start(Banner.java:213)
                                                                     at com.test.banner.MainActivity$1.handleMessage(MainActivity.java:35)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by MIkeeJY** [comment]
确实我也偶现这个情况

**Comment by youth5201314** [comment]
此问题已修复，用1.4.4
