### ISSUE TITLE
内存溢出怎么解决

### ISSUE THREAD

**Issue by wang709693972wei** [youth5201314/banner#598]
java.lang.OutOfMemoryError
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:878)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:845)
        at com.zhenai.loveguider.widget.widget.BannerRoundImageView.draw(BannerRoundImageView.java:52)
        at android.view.View.getDisplayList(View.java:14085)
        at android.view.View.getDisplayList(View.java:14127)
        at android.view.View.draw(View.java:14905)

**Comment by AlpsDog** [comment]
这个库我重构之后，加了缓存处理，老铁可以看看啊（我有点厚颜无耻了啊，哈哈）

**Comment by LackyVelice** [comment]
怎么解决的，我也遇到了，轮播的时间长了内存一直都在增加
