### ISSUE TITLE
banner运行时崩溃，咋回事  1.4.9

### ISSUE THREAD

**Issue by chentaishan** [youth5201314/banner#634]
at java.lang.reflect.Constructor.newInstance0!(Native method)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.createView(LayoutInflater.java:652)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   - locked <0x00bbdd94> (a java.lang.Object[])
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at com.youth.banner.Banner.initView(Banner.java:115)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at com.youth.banner.Banner.<init>(Banner.java:89)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at com.youth.banner.Banner.<init>(Banner.java:77)
2019-10-11 14:32:51.974 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at java.lang.reflect.Constructor.newInstance0!(Native method)
2019-10-11 14:32:51.975 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at com.youth.banner.Banner.initView(Banner.java:115)
2019-10-11 14:32:51.975 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.createView(LayoutInflater.java:652)
2019-10-11 14:32:51.982 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
2019-10-11 14:32:51.987 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at com.youth.banner.Banner.<init>(Banner.java:89)
2019-10-11 14:32:51.992 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.createView(LayoutInflater.java:652)
2019-10-11 14:32:51.992 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
2019-10-11 14:32:51.993 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at android.view.LayoutInflater.createView(LayoutInflater.java:652)
2019-10-11 14:32:51.993 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at com.youth.banner.Banner.<init>(Banner.java:89)
2019-10-11 14:32:51.993 25272-25272/com.example.day12_3 A/art: art/runtime/runtime.cc:403]   at com.youth.banner.Banner.<init>(Banner.java:77)

**Comment by yzm97448** [comment]
兄弟你这个问题解决了吗？我也出来了，，，

**Comment by chentaishan** [comment]
没有
