### ISSUE TITLE
当作空布局使用的异常

### ISSUE THREAD

**Issue by mayangyang-github** [youth5201314/banner#678]
直接new 出来或者 在xml 布局中写出来, 在不做任何设置(数据)之前, 会有异常, 希望做一些判断噢~
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageResource(int)' on a null object reference
        at com.youth.banner.Banner.initView(Banner.java:111)
        at com.youth.banner.Banner.<init>(Banner.java:96)
        at com.youth.banner.Banner.<init>(Banner.java:84)
```

**Comment by youth5201314** [comment]
确实有点问题已经修改，但是和你贴的不一样，你是怎么操作的？
