### ISSUE TITLE
java.lang.NullPointerException异常

### ISSUE THREAD

**Issue by weinierfei** [youth5201314/banner#691]
场景：banner数据没有加载完成.onstart方法执行了,导致了空异常

`java.lang.NullPointerException: Attempt to invoke virtual method 'int com.youth.banner.adapter.BannerAdapter.getItemCount()' on a null object reference
        at com.youth.banner.Banner.getItemCount(Banner.java:275)
        at com.youth.banner.Banner.access$100(Banner.java:38)
        at com.youth.banner.Banner$AutoLoopTask.run(Banner.java:245)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by typ19970** [comment]
+1

**Comment by jerry9433** [comment]
+1

**Comment by youth5201314** [comment]
没有复现这个错，但是也做了些改动，过几天发布，你们试下最新版看看还有错没。有的话在告诉我。

**Comment by lepaitianshi** [comment]
+1
