### ISSUE TITLE
android 9.0以上运行报错 java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by JasonTian23** [youth5201314/banner#718]
com.test.banner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.banner, PID: 7743
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipPath(Canvas.java:1007)
        at com.youth.banner.Banner.dispatchDraw(Banner.java:248)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.View.draw(View.java:19966)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.View.draw(View.java:19966)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20241)
        at android.widget.ScrollView.draw(ScrollView.java:1739)
        at android.view.View.updateDisplayListIfDirty(View.java:19113)
        at android.view.View.draw(View.java:19966)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20241)
        at android.view.View.updateDisplayListIfDirty(View.java:19113)
        at android.view.View.draw(View.java:19966)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.View.draw(View.java:19966)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.View.draw(View.java:19966)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.View.draw(View.java:19966)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.View.draw(View.java:19966)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20241)
        at com.android.internal.policy.DecorView.draw(DecorView.java:784)
        at android.view.View.updateDisplayListIfDirty(View.java:19113)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3405)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3195)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2564)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1534)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7408)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:888)
        at android.view.Choreographer.doFrame(Choreographer.java:819)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

修改如下可运行：
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
	canvas.clipPath(path);
} else {
	canvas.clipPath(path, Region.Op.REPLACE);
}

**Comment by youth5201314** [comment]
好的

**Comment by megachou** [comment]
当setBannerRound()时发生这个错误，其他正常。

**Comment by Ymars1990** [comment]
这个问题我也遇到过，需要重写一下dispatchDraw（）如题主那样处理

**Comment by youth5201314** [comment]
可以使用最新版本，已经修改
