### ISSUE TITLE
编译后运行报错 canScrollVertically null

### ISSUE THREAD

**Issue by navychang** [youth5201314/banner#719]
` Process: com.test.banner, PID: 9257
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10378)
        at androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl.onInitializeAccessibilityNodeInfo(ViewPager2.java:1017)
        at com.youth.banner.util.ProxyLayoutManger.onInitializeAccessibilityNodeInfo(ProxyLayoutManger.java:91)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10348)
        at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:74)
       `

**Comment by navychang** [comment]
Banner  init（）中
//      ProxyLayoutManger.setScrollProxy(this);
注销才行

**Comment by youth5201314** [comment]
这个问题已经优化了，下个版本提交
