### ISSUE TITLE
1.4.5 update（）方法更新图片无效

### ISSUE THREAD

**Issue by lijie815917** [youth5201314/banner#78]

**Comment by youth5201314** [comment]
怎么可能没有效果，我刚测试了的！你仔细看下demo呢？

**Comment by youth5201314** [comment]
怎么可能没有效果，我刚测试了的！你仔细看下demo呢？

**Comment by lijie815917** [comment]
我这边是不生效，我是先设置了一个空的list给setImages()方法，然后获取图片后再去更新update(),然后失效了，不能加载图片，我用的是Fresco加载器

**Comment by youth5201314** [comment]
看demo吧！你的方法明显有问题！

**Comment by lijie815917** [comment]
可以了，谢谢，和方法无关，是我自己误设置View GONE了

**Comment by lijie815917** [comment]
java.lang.ArithmeticException: divide by zero
                                                                          at com.youth.banner.Banner.onPageSelected(Banner.java:541)
                                                                          at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1931)
                                                                          at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:683)
                                                                          at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:667)
                                                                          at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2245)
                                                                          at com.youth.banner.view.BannerViewPager.onTouchEvent(BannerViewPager.java:23)
                                                                          at android.view.View.dispatchTouchEvent(View.java:9481)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2660)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2304)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
                                                                          at com.youth.banner.Banner.dispatchTouchEvent(Banner.java:462)
更新图片后，能正常显示，滚动然后崩溃了~

**Comment by youth5201314** [comment]
看最新的demo，现在的demo要详细很多，你自己对照吧！

**Comment by MIkeeJY** [comment]
@lijie815917  你用fresco加载的时候需要确定当前的wifi网络跟图片url是否可用

**Comment by smxy34** [comment]
请问，请求网络图片，如果图片被重命名的情况，如何更新图片？
