### ISSUE TITLE
升级Androidx后停留一段时间退出闪退 这个问题怎么解决有大佬遇到吗？

### ISSUE THREAD

**Issue by 287432799** [youth5201314/banner#809]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager2.widget.ViewPager2.unregisterOnPageChangeCallback(androidx.viewpager2.widget.ViewPager2$OnPageChangeCallback)' on a null object reference
        at com.youth.banner.Banner.destroy(Banner.java:582)
        at com.youth.banner.Banner.onDestroy(Banner.java:878)
        at com.youth.banner.util.BannerLifecycleObserverAdapter.onDestroy(BannerLifecycleObserverAdapter.java:32)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:316) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:334) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123) 
        at androidx.lifecycle.ReportFragment.onDestroy(ReportFragment.java:108) 
        at android.app.Fragment.performDestroy(Fragment.java:2782) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3055) 
        at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3035) 
        at android.app.FragmentController.dispatchDestroy(FragmentController.java:248) 
        at android.app.Activity.performDestroy(Activity.java:7622) 
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307) 
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4798) 
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4832) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:151) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:76) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1988) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:232) 
        at android.app.ActivityThread.main(ActivityThread.java:7240) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by youth5201314** [comment]
能详细写下你的操作步骤呢？再贴下你怎么用的，我定位下问题！
