### ISSUE TITLE
在activity之间频繁切换，app crash了

### ISSUE THREAD

**Issue by linguohui** [youth5201314/banner#839]
异常信息
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.daima.livechat.app, PID: 29148
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.viewpager2.widget.ViewPager2.isUserInputEnabled()' on a null object reference
        at com.youth.banner.Banner.dispatchTouchEvent(Banner.java:200)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
        at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2850)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3749)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3810)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6753)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:6730)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:396)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4498)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by liujun1223** [comment]
空指针异常


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Goal Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 下午5:58
收件人:&nbsp;"youth5201314/banner"<banner@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[youth5201314/banner] 在activity之间频繁切换，app crash了 (#839)





 
异常信息
 E/AndroidRuntime: FATAL EXCEPTION: main
 Process: tech.daima.livechat.app, PID: 29148
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.viewpager2.widget.ViewPager2.isUserInputEnabled()' on a null object reference
 at com.youth.banner.Banner.dispatchTouchEvent(Banner.java:200)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
 at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2850)
 at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3749)
 at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3810)
 at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6753)
 at android.view.ViewRootImpl.die(ViewRootImpl.java:6730)
 at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
 at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:396)
 at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
 at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4498)
 at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6669)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by linguohui** [comment]
应该是我的问题，我的返回按钮在banner上面，点击事件处理后activity销毁时，事件透给了banner处理，导致空指针
