### ISSUE TITLE
那个banner点击偶现还是会越界。。position从1开始

### ISSUE THREAD

**Issue by MIkeeJY** [youth5201314/banner#91]
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                         at java.util.ArrayList.get(ArrayList.java:308)
                                                                         at com.xxx.fragment.HomeFragment$4$1.OnBannerClick(HomeFragment.java:195)
                                                                         at com.xxx.view.banner.Banner$BannerPagerAdapter$1.onClick(Banner.java:500)
                                                                         at android.view.View.performClick(View.java:5207)
                                                                         at android.view.View$PerformClick.run(View.java:21177)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by youth5201314** [comment]
你用的不是远程依赖的吧！我第500行可不是点击事件！你把代码考到你的工程里，然后报错了，你让我怎么解决呢？你用远程依赖的方式测试如果有问题给我反馈下日志吧！

**Comment by MIkeeJY** [comment]
@imliujun 是这个样子的最后一张图过渡到第一张的时候 如果快速点击会出现

**Comment by MIkeeJY** [comment]
@imliujun 试下1.4.6新版本

**Comment by imliujun** [comment]
@MIkeeJY 现在已经更新到1.4.7 了,内部打印下标的代码被注掉了，不知道还会不会越界，反正我在点击事件里面做了判断，不会导致崩溃了

**Comment by youth5201314** [comment]
你应该仔细看下代码，那不叫越界，我返回的值都不一样，打印的值不是返回前台的，那是我调试无限循环用的。

**Comment by imliujun** [comment]
假设我的imageList.size() = 5;
```java
public Banner setImages(List<?> imageUrls) {
        this.imageUrls = imageUrls;
        this.count = imageUrls.size();    //count = size = 5
        return this;
}

private void setImageList(List<?> imagesUrl) {
        if (imagesUrl == null || imagesUrl.size() <= 0) {
            Log.e(tag, "Please set the images data.");
            return;
        }
        initImages();
        for (int i = 0; i <= count + 1; i++) {//这里初始化图片的时候count+1 = 6
            View imageView = null;
            if (imageLoader != null) {
                imageView = imageLoader.createImageView(context);
            }
            if (imageView == null) {
                imageView = new ImageView(context);
            }
            setScaleType(imageView);
            Object url = null;
            if (i == 0) {
                url = imagesUrl.get(count - 1);
            } else if (i == count + 1) {
                url = imagesUrl.get(0);
            } else {
                url = imagesUrl.get(i - 1);
            }
            imageViews.add(imageView);   //imageViews.size() 最终=7,因为i从0到6
            if (imageLoader != null)
                imageLoader.displayImage(context, url, imageView);
            else
                Log.e(tag, "Please set images loader.");
        }
        setData();
    }


class BannerPagerAdapter extends PagerAdapter {

        @Override
        public int getCount() {
            return imageViews.size();// 返回 7
        }

        @Override
        public Object instantiateItem(ViewGroup container, final int position) {
            container.addView(imageViews.get(position));
            View view = imageViews.get(position);
            if (listener != null) {
                view.setOnClickListener(new OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        //position 的范围是0-6，外面的imageList.size()=5，这里直接传过去会不会越界？
                        listener.OnBannerClick(position);
                    }
                });
            }
            return view;
        }

       
    }
}
```

**Comment by youth5201314** [comment]
@MIkeeJY  @imliujun   感谢你们的反馈，还是旁观者清啊，你们可以用下面的方式获取大最真实的位置，可以避免出现越界，我下一个版本更新，这样做返回的就是从0开始了！
/**
     *  返回真实的位置
     *
     * @param position 为我返回的位置
     * @return
     */
    private int toRealPosition(int position) {
        int realPosition = (position - 1) % count;//count是你的图片真实数量
        if (realPosition < 0)
            realPosition += count;
        return realPosition;
    }
你可以本地依赖再instantiateItem方法中调用，也可以在我的点击事件中调用

**Comment by RockyLin** [comment]
版本：1.4.8
问题描述：5张图片轮播，public void OnBannerClick(int position)， 返回的position 取值从1-5.
点击第一张，position返回1
手动滑到第二张，点position返回2，
手动滑到第三张，点position返回3，

然后问题来了：
**手动滑回到第二张，点position1。**

往前滑是正常的，往后滑的Position有时候不对。

**Comment by coolhades** [comment]
@RockyLin 
版本：1.4.9
手动往回滑的position确实不对 从0、1、2往回滑pos变成0
@youth5201314

**Comment by RockyLin** [comment]
已换lib:     compile 'cn.bingoogolapple:bga-banner:2.1.7@aar'

@coolhades
