### ISSUE TITLE
越界崩溃问题

### ISSUE THREAD

**Issue by lantee** [youth5201314/banner#928]
怀疑是重新设置轮播器数据源引起的崩溃
以下是崩溃代码 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBannerViewHolder{3426020 position=4 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{1df2ac VFED..... ........ 0,0-1080,538 #1}, adapter:cn.yango.greenhome.ui.main.HomepageFragment$AdAdapter@9b8eb75, layout:com.youth.banner.util.ScrollSpeedManger@cf8170a, context:cn.yango.greenhome.ui.main.MainActivity@bd722bf
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by youth5201314** [comment]
这是因为进行数据移除和数据增加时，数据集没有保持一致！adapter是用户自定义实现的，数据操作都可以自己随意操作的。不用频繁的调用setAdapter()
