### ISSUE TITLE
MainActivity.java里 ImageAdapter adapter = new ImageAdapter(DataBean.getTestData3());报错

### ISSUE THREAD

**Issue by zhugscn** [youth5201314/banner#963]
运行环境android studio 4.6,   android设备是定制android7.1  , 原来是getTestData()不报错, 换成getTestData3()报以下错误：（运行即崩溃）

2020-11-24 17:53:52.277 24538-24538/com.test.banner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.banner, PID: 24538
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.test.banner.d.a.a(:46)
        at com.test.banner.d.a.onBindView(:15)
        at com.youth.banner.adapter.BannerAdapter.onBindViewHolder(:41)
        at androidx.recyclerview.widget.RecyclerView$h.onBindViewHolder(:7178)
        at androidx.recyclerview.widget.RecyclerView$h.bindViewHolder(:7258)
        at androidx.recyclerview.widget.RecyclerView$w.a(:6125)
        at androidx.recyclerview.widget.RecyclerView$w.a(:6391)
        at androidx.recyclerview.widget.RecyclerView$w.b(:6231)
        at androidx.recyclerview.widget.RecyclerView$w.d(:6227)
        at androidx.recyclerview.widget.LinearLayoutManager$c.a(:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(:4230)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(:3630)
        at android.view.View.measure(View.java:19873)
        at android.view.ViewGroup.measureChild(ViewGroup.java:6054)
        at androidx.viewpager2.widget.ViewPager2.onMeasure(:498)
        at android.view.View.measure(View.java:19873)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19873)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19873)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(:705)
        at android.view.View.measure(View.java:19873)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(:146)
        at android.view.View.measure(View.java:19873)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(:490)
        at android.view.View.measure(View.java:19873)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19873)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19873)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:819)
        at android.view.View.measure(View.java:19873)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:755)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method)
2020-11-24 17:53:52.277 24538-24538/com.test.banner E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by youth5201314** [comment]
两个数据都不一样啊，你仔细看代码啊，ImageAdapter和ImageNetAdapter的作用都不一样，分别列举不同使用情况
