### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by lpysjl** [youth5201314/banner#966]
--logversion:utracea
Process Name: &#39;com.keyschool.app&#39;
Thread Name: &#39;main&#39;
Back traces starts.
android.view.InflateException: Binary XML file line #126 in com.taobao.gxl.sophix.hotifx:layout/fragment_found: Binary XML file line #126 in com.taobao.gxl.sophix.hotifx:layout/fragment_found: Error inflating class com.youth.banner.Banner
Caused by: android.view.InflateException: Binary XML file line #126 in com.taobao.gxl.sophix.hotifx:layout/fragment_found: Error inflating class com.youth.banner.Banner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:864)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
	at com.github.obsessive.library.base.BaseLazyFragment.onCreateView(BaseLazyFragment.java:93)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:259)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:24755)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1002)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
	at android.view.View.measure(View.java:24755)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6996)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:24755)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6996)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
	at android.view.View.measure(View.java:24755)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6996)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24755)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6996)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
	at android.view.View.measure(View.java:24755)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6996)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:935)
	at android.view.View.measure(View.java:24755)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3254)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1996)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2323)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1879)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8170)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
	at android.view.Choreographer.doFrame(Choreographer.java:776)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8285)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1052)
Caused by: java.lang.ClassCastException: com.youth.banner.Banner cannot be cast to com.youth.banner.view.BannerViewPager
	at com.youth.banner.Banner.initView(Banner.java:104)
	at com.youth.banner.Banner.&lt;init&gt;(Banner.java:96)
	at com.youth.banner.Banner.&lt;init&gt;(Banner.java:84)
	... 70 more
Back traces ends.

pixel android 9.0

**Comment by lpysjl** [comment]
看起来像是热更新导致的，但是热更新没有修改相关内容  - -。
